-- Org-scoped AI drafting credits (platform feature). Not asset gateway metering.
-- Also: editors may update unpublished policy_documents; published stays owner/admin.

CREATE TABLE IF NOT EXISTS public.org_ai_credit_balances (
  org_id uuid PRIMARY KEY REFERENCES public.organisations(id) ON DELETE CASCADE,
  balance_cents integer NOT NULL DEFAULT 0 CHECK (balance_cents >= 0),
  -- 500 = $5 USD monthly allowance (not GBP).
  monthly_allowance_cents integer NOT NULL DEFAULT 500 CHECK (monthly_allowance_cents >= 0),
  low_balance_cents integer NOT NULL DEFAULT 50 CHECK (low_balance_cents >= 0),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.org_ai_credit_balances IS
  'Spendable platform AI credit balance per organisation for policy drafting and similar features.';
COMMENT ON COLUMN public.org_ai_credit_balances.balance_cents IS
  'Remaining prepaid credit in USD cents.';
COMMENT ON COLUMN public.org_ai_credit_balances.monthly_allowance_cents IS
  'Monthly refill cap in USD cents ($5 = 500). Subscription refill grants max(0, allowance - balance); never stacks a second full allowance.';

CREATE TABLE IF NOT EXISTS public.org_ai_credit_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id uuid NOT NULL REFERENCES public.organisations(id) ON DELETE CASCADE,
  entry_type text NOT NULL CHECK (entry_type IN (
    'grant_subscription',
    'grant_topup',
    'grant_manual',
    'debit_draft_policy',
    'adjust'
  )),
  amount_cents integer NOT NULL,
  balance_after_cents integer NOT NULL CHECK (balance_after_cents >= 0),
  tier text,
  model text,
  input_tokens integer CHECK (input_tokens IS NULL OR input_tokens >= 0),
  output_tokens integer CHECK (output_tokens IS NULL OR output_tokens >= 0),
  stripe_event_id text,
  actor_user_id uuid REFERENCES auth.users(id),
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS org_ai_credit_ledger_org_created_idx
  ON public.org_ai_credit_ledger (org_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS org_ai_credit_ledger_stripe_event_uidx
  ON public.org_ai_credit_ledger (stripe_event_id)
  WHERE stripe_event_id IS NOT NULL;

COMMENT ON TABLE public.org_ai_credit_ledger IS
  'Append-only credit/debit history for org AI balances. Stripe events key by stripe_event_id for idempotency.';

ALTER TABLE public.org_ai_credit_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.org_ai_credit_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS org_ai_credit_balances_select ON public.org_ai_credit_balances;
CREATE POLICY org_ai_credit_balances_select ON public.org_ai_credit_balances
  FOR SELECT TO authenticated
  USING (is_org_member(org_id));

DROP POLICY IF EXISTS org_ai_credit_ledger_select ON public.org_ai_credit_ledger;
CREATE POLICY org_ai_credit_ledger_select ON public.org_ai_credit_ledger
  FOR SELECT TO authenticated
  USING (is_org_member(org_id));

REVOKE ALL ON TABLE public.org_ai_credit_balances FROM anon, authenticated;
REVOKE ALL ON TABLE public.org_ai_credit_ledger FROM anon, authenticated;
GRANT SELECT ON TABLE public.org_ai_credit_balances, public.org_ai_credit_ledger TO authenticated;
GRANT ALL ON TABLE public.org_ai_credit_balances, public.org_ai_credit_ledger TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.org_ai_credit_ledger_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.org_ai_credit_debit(
  p_org_id uuid,
  p_amount_cents integer,
  p_entry_type text,
  p_tier text DEFAULT NULL,
  p_model text DEFAULT NULL,
  p_input_tokens integer DEFAULT NULL,
  p_output_tokens integer DEFAULT NULL,
  p_actor_user_id uuid DEFAULT NULL,
  p_meta jsonb DEFAULT '{}'::jsonb
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_bal integer;
BEGIN
  IF p_amount_cents IS NULL OR p_amount_cents <= 0 THEN
    RAISE EXCEPTION 'debit amount must be positive';
  END IF;
  IF p_entry_type NOT IN ('debit_draft_policy', 'adjust') THEN
    RAISE EXCEPTION 'invalid debit entry_type';
  END IF;

  INSERT INTO public.org_ai_credit_balances (org_id, balance_cents)
  VALUES (p_org_id, 0)
  ON CONFLICT (org_id) DO NOTHING;

  SELECT balance_cents INTO v_bal
  FROM public.org_ai_credit_balances
  WHERE org_id = p_org_id
  FOR UPDATE;

  IF v_bal < p_amount_cents THEN
    RAISE EXCEPTION 'insufficient_ai_credits' USING ERRCODE = 'P0001';
  END IF;

  v_bal := v_bal - p_amount_cents;

  UPDATE public.org_ai_credit_balances
  SET balance_cents = v_bal, updated_at = now()
  WHERE org_id = p_org_id;

  INSERT INTO public.org_ai_credit_ledger (
    org_id, entry_type, amount_cents, balance_after_cents,
    tier, model, input_tokens, output_tokens, actor_user_id, meta
  ) VALUES (
    p_org_id, p_entry_type, -p_amount_cents, v_bal,
    p_tier, p_model, p_input_tokens, p_output_tokens, p_actor_user_id, p_meta
  );

  RETURN v_bal;
END;
$$;

-- Monthly subscription refill-to-cap (NOT blind +allowance).
-- grant = max(0, allowance - current_balance)
CREATE OR REPLACE FUNCTION public.org_ai_credit_refill_subscription(
  p_org_id uuid,
  p_stripe_event_id text,
  p_allowance_cents integer DEFAULT NULL,
  p_meta jsonb DEFAULT '{}'::jsonb
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_bal integer;
  v_allowance integer;
  v_grant integer;
BEGIN
  IF p_stripe_event_id IS NULL OR length(trim(p_stripe_event_id)) = 0 THEN
    RAISE EXCEPTION 'stripe_event_id required for subscription refill';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.org_ai_credit_ledger WHERE stripe_event_id = p_stripe_event_id
  ) THEN
    SELECT balance_cents INTO v_bal FROM public.org_ai_credit_balances WHERE org_id = p_org_id;
    RETURN COALESCE(v_bal, 0);
  END IF;

  INSERT INTO public.org_ai_credit_balances (org_id, balance_cents)
  VALUES (p_org_id, 0)
  ON CONFLICT (org_id) DO NOTHING;

  SELECT balance_cents,
         COALESCE(p_allowance_cents, monthly_allowance_cents)
  INTO v_bal, v_allowance
  FROM public.org_ai_credit_balances
  WHERE org_id = p_org_id
  FOR UPDATE;

  IF v_allowance IS NULL OR v_allowance < 0 THEN
    RAISE EXCEPTION 'invalid allowance';
  END IF;

  v_grant := GREATEST(0, v_allowance - v_bal);

  IF v_grant > 0 THEN
    v_bal := v_bal + v_grant;
    UPDATE public.org_ai_credit_balances
    SET balance_cents = v_bal, updated_at = now()
    WHERE org_id = p_org_id;
  END IF;

  INSERT INTO public.org_ai_credit_ledger (
    org_id, entry_type, amount_cents, balance_after_cents, stripe_event_id, meta
  ) VALUES (
    p_org_id,
    'grant_subscription',
    v_grant,
    v_bal,
    p_stripe_event_id,
    coalesce(p_meta, '{}'::jsonb) || jsonb_build_object(
      'allowance_cents', v_allowance,
      'grant_cents', v_grant
    )
  );

  RETURN v_bal;
END;
$$;

CREATE OR REPLACE FUNCTION public.org_ai_credit_grant(
  p_org_id uuid,
  p_amount_cents integer,
  p_entry_type text,
  p_stripe_event_id text DEFAULT NULL,
  p_meta jsonb DEFAULT '{}'::jsonb
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_bal integer;
BEGIN
  IF p_amount_cents IS NULL OR p_amount_cents <= 0 THEN
    RAISE EXCEPTION 'grant amount must be positive';
  END IF;
  IF p_entry_type NOT IN ('grant_topup', 'grant_manual', 'adjust') THEN
    RAISE EXCEPTION 'invalid grant entry_type — use org_ai_credit_refill_subscription for subscription allowance';
  END IF;

  IF p_stripe_event_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM public.org_ai_credit_ledger WHERE stripe_event_id = p_stripe_event_id
  ) THEN
    SELECT balance_cents INTO v_bal FROM public.org_ai_credit_balances WHERE org_id = p_org_id;
    RETURN COALESCE(v_bal, 0);
  END IF;

  INSERT INTO public.org_ai_credit_balances (org_id, balance_cents)
  VALUES (p_org_id, 0)
  ON CONFLICT (org_id) DO NOTHING;

  SELECT balance_cents INTO v_bal
  FROM public.org_ai_credit_balances
  WHERE org_id = p_org_id
  FOR UPDATE;

  v_bal := v_bal + p_amount_cents;

  UPDATE public.org_ai_credit_balances
  SET balance_cents = v_bal, updated_at = now()
  WHERE org_id = p_org_id;

  INSERT INTO public.org_ai_credit_ledger (
    org_id, entry_type, amount_cents, balance_after_cents, stripe_event_id, meta
  ) VALUES (
    p_org_id, p_entry_type, p_amount_cents, v_bal, p_stripe_event_id, p_meta
  );

  RETURN v_bal;
END;
$$;

REVOKE ALL ON FUNCTION public.org_ai_credit_debit FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.org_ai_credit_refill_subscription FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.org_ai_credit_grant FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.org_ai_credit_debit TO service_role;
GRANT EXECUTE ON FUNCTION public.org_ai_credit_refill_subscription TO service_role;
GRANT EXECUTE ON FUNCTION public.org_ai_credit_grant TO service_role;

-- Editors may edit unpublished drafts; published body stays owner/admin.
DROP POLICY IF EXISTS policy_docs_update ON public.policy_documents;
DROP POLICY IF EXISTS policy_docs_update_admin ON public.policy_documents;
DROP POLICY IF EXISTS policy_docs_update_editor_draft ON public.policy_documents;

CREATE POLICY policy_docs_update_admin ON public.policy_documents
  FOR UPDATE TO authenticated
  USING (has_org_role(org_id, ARRAY['owner'::text, 'admin'::text]))
  WITH CHECK (has_org_role(org_id, ARRAY['owner'::text, 'admin'::text]));

CREATE POLICY policy_docs_update_editor_draft ON public.policy_documents
  FOR UPDATE TO authenticated
  USING (
    has_org_role(org_id, ARRAY['editor'::text])
    AND published_at IS NULL
  )
  WITH CHECK (
    has_org_role(org_id, ARRAY['editor'::text])
    AND published_at IS NULL
  );
