-- Phase 8: governed Anthropic gateway.
-- Gateway bearer tokens are capabilities; only SHA-256 hashes are persisted.

CREATE TABLE IF NOT EXISTS public.asset_gateway_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES public.organisations(id) ON DELETE CASCADE,
  asset_id uuid NOT NULL REFERENCES public.ai_systems(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  label text NOT NULL CHECK (char_length(label) BETWEEN 1 AND 80),
  created_by uuid NOT NULL REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz
);

CREATE INDEX IF NOT EXISTS asset_gateway_tokens_asset_idx
  ON public.asset_gateway_tokens (asset_id, created_at DESC);

CREATE INDEX IF NOT EXISTS asset_gateway_tokens_active_hash_idx
  ON public.asset_gateway_tokens (token_hash)
  WHERE revoked_at IS NULL;

COMMENT ON TABLE public.asset_gateway_tokens IS
  'Asset-scoped gateway capabilities. Plaintext tokens are returned once and are never stored.';
COMMENT ON COLUMN public.asset_gateway_tokens.token_hash IS
  'Lowercase SHA-256 digest of the gateway bearer token.';

ALTER TABLE public.asset_gateway_tokens ENABLE ROW LEVEL SECURITY;
-- No client policies: token lifecycle is mediated by asset-gateway-token.

CREATE TABLE IF NOT EXISTS public.asset_usage_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_id uuid NOT NULL REFERENCES public.ai_systems(id) ON DELETE CASCADE,
  org_id uuid NOT NULL REFERENCES public.organisations(id) ON DELETE CASCADE,
  input_tokens integer NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
  output_tokens integer NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
  model text NOT NULL,
  source text NOT NULL DEFAULT 'gateway' CHECK (source IN ('gateway')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS asset_usage_events_asset_created_idx
  ON public.asset_usage_events (asset_id, created_at DESC);

CREATE INDEX IF NOT EXISTS asset_usage_events_org_created_idx
  ON public.asset_usage_events (org_id, created_at DESC);

COMMENT ON TABLE public.asset_usage_events IS
  'Prompt-free token telemetry written by governed provider gateways.';

ALTER TABLE public.asset_usage_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS asset_usage_events_select ON public.asset_usage_events;
CREATE POLICY asset_usage_events_select ON public.asset_usage_events
  FOR SELECT
  USING (is_org_member(org_id));

-- Gateway and token functions use a privileged server client after performing
-- their own capability or owner/admin authorization checks.
REVOKE ALL ON TABLE public.asset_gateway_tokens FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.asset_usage_events FROM anon, authenticated;
GRANT SELECT ON TABLE public.asset_usage_events TO authenticated;
GRANT ALL ON TABLE public.asset_gateway_tokens, public.asset_usage_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.asset_usage_events_id_seq TO service_role;
